[inner]
version = "0.1.0" # 配置模板版本

[telegram_bot]
token = ""                                      # Telegram Bot Token（必填）
api_base = "https://api.telegram.org"           # API 基础地址
poll_timeout = 20                               # getUpdates 超时（秒）
allowed_updates = ["message", "edited_message"]
proxy_enabled = false                           # 是否启用代理
proxy_url = ""                                  # 代理地址，例如：socks5://127.0.0.1:1080 或 http://127.0.0.1:7890
proxy_from_env = false                          # 是否从环境变量读取代理（HTTP(S)_PROXY/NO_PROXY）

[maibot_server]
# 与 MaiBot Core 的 ws 连接设置（示例：ws://<host>:<port>/ws）
host = "localhost"
port = 8000

[chat]
group_list_type = "whitelist"   # whitelist/blacklist
group_list = []
private_list_type = "whitelist"
private_list = []
ban_user_id = []
enable_poke = false

[debug]
level = "INFO"                       # 适配器日志级别：TRACE/DEBUG/INFO/WARNING/ERROR/CRITICAL
maim_message_level = "INFO"          # maim_message 子系统日志级别
to_file = false                       # 是否写入文件
file_path = "logs/telegram-adapter.log"
rotation = "10 MB"                   # 轮转大小或时间：如 "10 MB"、"1 day"
retention = "7 days"                 # 保留时间或数量：如 "7 days"、"14 files"
serialize = false                    # 文件日志输出 JSON
backtrace = false                    # 异常时输出完整回溯
diagnose = false                     # 更详细的异常诊断
